falkTX/Carla

- source/native-plugins/resources/midiseq-ui
updated UI for midisequencer with note add/remove and some other stuff.
keys:
F - insert mode
D - velocity mode
A - select/deselect all
Del/Backspace - delete selected
> new midisequencer UI

- source/native-plugins/resources/midiseq-ui
https://github.com/falkTX/Carla/pull/198#issuecomment-71575556
> including time signature information for midiseq note-on

- source/native-plugins/resources/midiseq-ui
I also included code for moving the playhead according to the transport. Right now since self.fTransportInfo only updates frames it only works correctly with 120bpm since I just hardcoded a value that worked. I think it would work with any bpm if we could pass ticks instead (it's in self.fTransportInfo already but doesn't seem to update).
> use 48 ppq for midiseq-ui

- source/carla_host.py
- source/carla_panels.py
- source/carla_skin.py
- source/carla_widgets.py
http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html
> [fix][PyQt5.6]: launch errors; add plugin errors

- source/Makefile.mk
> Add option to allow disabling stripping of binaries

- source/patchcanvas.py
- source/patchcanvas_theme.py
- source/widgets/canvaspreviewframe.py
Here are changes, which fix look for antialiased borders. It is enabled for both canvas and minimap, slightly changing look for map image, while 2d cursor gets same antialiasing fix.
Note: this branch is based on mouse-connection-cut, which was confirmed to be ok, but is still opened.
> Lines hinting

- source/carla_host.py
Implements https://github.com/falkTX/Carla/issues/360. It prompts for confirmation even if there is only one plugin loaded. 
I hope I did that right :)
> Add confirmation dialog for Remove All and New File

- source/frontend/carla_host.py
- source/frontend/widgets/paramspinbox.py
- source/theme/CarlaStyle.cpp
- source/theme/CarlaStylePrivate.hpp
Fixed some artefacts in builtin fusion style + spinbox size and some colors.
Fileview in sidebar got 1px spacing for internal elements.
> Frontend widget enhancements

- resources/ui/carla_host.ui
- source/frontend/carla_host.py
- source/frontend/widgets/canvaspreviewframe.py
Sidebar: 1px browser elements spacing
Minimap:
- better frame, created from tab-less tabwidget,
- update on each selection change,
- some color scheme awareness,
- full resize (vertical too),
- better cursor blending,
- mouse restriction during movement,
- scale mode.
> Minimap enhancements

- source/Makefile.mk
- source/backend/plugin/CarlaPluginFluidSynth.cpp
- source/discovery/carla-discovery.cpp
It needs a new pull request for develop branch. Will close the other one
V1 -> V2:
* rebase against develop branch
* rename function & vars
* add missing 'sbFluidDefaultsStored = true;'
> Fixes for fluidsynth >= 2.0.0 V2

- source/native-plugins/audio-gain.c
Added low pass filter on gain control, to prevent clicking noises
> Add filter on gain control of audio-gain plugin

- .travis.yml
This PR removes old syntax in favor of a more recent one
> Update Travis syntax

- source/frontend/carla_widgets.py
> Fix incorrect base conversion for midi CC numbers

- source/theme/CarlaStyle.cpp
Fix build failure with qtgui-5.15.0/gcc10
> Add missing QPainterPath include

- resources/resources.qrc
- resources/ui/carla_edit.ui
- resources/ui/carla_plugin_calf.ui
- resources/ui/carla_plugin_classic.ui
- resources/ui/carla_plugin_compact.ui
- resources/ui/carla_plugin_default.ui
- resources/ui/carla_plugin_presets.ui
- source/frontend/carla_skin.py
- source/frontend/carla_widgets.py
- source/frontend/widgets/ledbutton.cpp
- source/frontend/widgets/ledbutton.py
- source/frontend/widgets/scalablebutton.py
- source/frontend/widgets/scalabledial.py
- source/theme/CarlaStyle.cpp
Code preparation for scalable LEDs, Dials and Buttons
_This is part 1 on a serie of PRs addressing some blurry UI elements on HiDPI displays._
> Fully Scalable UI Part 1

- resources/scalable/button_edit-black.svg
- resources/scalable/button_edit-white.svg
- resources/scalable/button_edit_down-black.svg
- resources/scalable/button_edit_down-white.svg
- resources/scalable/button_edit_hover-black.svg
- resources/scalable/button_edit_hover-white.svg
- resources/scalable/button_gui-white.svg
- resources/scalable/button_gui_down-white.svg
- resources/scalable/button_gui_hover-white.svg
- resources/scalable/button_off.svg
- resources/scalable/button_on.svg
- resources/scalable/dial_03.svg
- resources/scalable/dial_03d.svg
- resources/scalable/dial_04.svg
- resources/scalable/dial_04d.svg
- resources/scalable/led_blue.svg
- resources/scalable/led_green.svg
- resources/scalable/led_off.svg
- resources/scalable/led_red.svg
- resources/scalable/led_yellow.svg
- resources/ui/carla_plugin_default.ui
- source/frontend/widgets/scalabledial.py
Add default rack LEDs, dials and buttons SVGs
_This is part 2 on a serie of PRs addressing some blurry UI elements on HiDPI displays._
> Fully Scalable UI Part 2

- .gitignore
- Makefile
This allows to create a local file `Makefile.user.mk` to locally keep configuration variables (PREFIX etc).
> Makefile user variables

- source/modules/jsusfx/source/jsusfx.cpp
jsusfx does supports ansi windows paths only, this work should fix that.
> jsfx: windows unicode path support

- source/frontend/widgets/digitalpeakmeter.py
- source/frontend/widgets/scalabledial.py
Hello,
I traced the drawing errors and was able to get the meters and knobs working again. Plugins show up in the rack as intended.
#1549
I tested it successfully on my machine. I guess it should work on older python versions, too.
Best regards,
Oliver
> Fixed unexpected type errors #1549

- source/utils/CarlaLv2Utils.hpp
some plugins use sidechain groups instead of isSideChain so the previous implementation wasn't working for e.g. LSP Sidechain Compressor.
I have verified that this change works
> lv2: mark port as sidechain if part of a sidechain group

- data/appdata.xml
The screenshot tag shouldn't contain more than one image
> Move second image to it's own screenshot tag

- source/backend/utils/Information.cpp
> missing </li> code
