resources/ui/carla_host.ui
source/carla_host.py

This defaults to the panel still showing up on newly updated versions.

Add a hide file browser menu option (fixes #199)

---

source/utils/CarlaString.hpp

Some VST plugins want to save a large binary chunk of state. For example,
Drumlab inside Kontakt 5 saves 1.5MB of data. We shouldn't allocate that
much on the stack.

Fix #380: Limit stack allocation during base64 encoding

---

Makefile

I build carla with make -j8; these patches fix a couple of dependency problems that cause occasional parallel make failures.

Fix a couple of parallel build problems

---

source/native-plugins/_data.all.cpp
source/native-plugins/_data.base.cpp
source/native-plugins/midi-transpose.c

Works well both as internal and lv2 plugin.
Only issue is that the internal plugin still appears to only have 1 parameter from the "add plugin" window.

add semitones parameter to midi-transpose plugin

---

source/modules/hylia/link/asio/impl/error_code.ipp

`char *strerror_r(int errnum, char *buf, size_t buflen);` is only mostly not available on linux systems without GLIBC. (e.g. Alpine linux or Void Linux with musl)

Only use GNU-specific char *strerror on systems with GLIBC

---

source/includes/CarlaDefines.h
source/modules/water/memory/ByteOrder.h

I don't know arm64 (or x86 asm) but the build does error with
```
../../modules/water/memory/ByteOrder.h:157:42: error: impossible constraint in 'asm'
asm("bswap %%eax" : "=a"(n) : "a"(n));
```
which is probably a indication that this is not arm64 assembly :D

Do not use x86 asm with arm64

---

source/carla_skin.py

Fixes text for plugin knobs being clipped in some desktop environments.

Set font size for plugin preset and midi/audio indicator labels

---

source/utils/CarlaPluginUI.cpp

Add X _NET_WM_WINDOW_TYPE flags to plugin windows so they work equally well on tiling window manages and floating WM.
Tested with QTile 2869.95919912 and XFCE 4.12.1
I consider this a trivial change which will not create any copyright for me.

Add X _NET_WM_WINDOW_TYPE flags to plugin windows 

---

source/frontend/patchcanvas.py

I still got sitation, when signal from deselected port comes after
selected one (i.e. select both ends with Ctrl, then select input end).

More reliable connection line (de)selection

---

source/frontend/patchcanvas.py

Added additional cosmetic-type layer to connection lines and OpenOctave theme port lights, making these elements distinguishable on tiniest scales on minimap.

Canvas tiny scale visibility

---

data/build-haiku.sh
data/carla
data/carla-control
data/carla-database
data/carla-jack-multi
data/carla-jack-single
data/carla-libdir
data/carla-patchbay
data/carla-rack
data/carla-settings

Previously, running Carla from this script would give the error, likely because the shell interpreter is not understand the more advanced syntax. Now uses simpler syntax.
`/usr/bin/carla: 14: export: Desktop:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: bad variable name`
Note: Alternatively, to use the previous syntax, the script must be using #!/bin/bash
(Tested on Ubuntu 18.04.1)

Fixed shell export syntax

---

source/bridges-plugin/CarlaBridgePlugin.cpp

Include <signal.h> in order to make `kill`, `SIGKILL` available.

Fix a build error on FreeBSD

---

source/jackbridge/JackBridge1.cpp

The type of `JackBridge::client_open_ptr` is:
jack_client_t* (*)(const char*, jack_options_t, jack_status_t*)
`client_open_ptr` is set to the address of `jack_client_open` (loaded via `dlopen`/`dlsym`), but the signature of `jack_client_open` is:
jack_client_t* jack_client_open(const char*, jack_options_t, jack_status_t*, ...)
`jack_client_open` is variadic, while `client_open_ptr` is not. PowerPC segfaults when calling a variadic function through a non-variadic pointer, as PowerPC reserves different amounts of stack space when calling a variadic vs. non-variadic function. In this case, `jack_client_open` assumes the caller allocated more space than it actually did, so it overwrites parts of the caller's stack frame that were not intended to be modified.
This PR changes the type of …

Fix segfault on PowerPC

---

data/carla-native-plugin.pc
data/carla-standalone.pc
data/carla-utils.pc

from IRC
```
<alextee> falktx, i get "/usr/bin/ld: cannot find rpath=/usr/lib/carla: No such file or directory" when using carla-native-plugin from pkgconfig
...
<alextee> falktx, i asked in #mesonbuild and it looks like the --libs of carla-native-plugin is wrong
<alextee> it currently says: -Wl,rpath=/usr/lib/carla -L/usr/lib/carla -lcarla_native-plugin
<alextee> but i was told it should be "-Wl,-rpath,/usr/lib/carla"
```
using `-Wl,-rpath,...` instead of `-Wl,rpath=...` made by build succeed
I think the problem is not the `=` but the missing `-` before rpath:
https://stackoverflow.com/a/15667612
EDIT:
changed to `-Wl,-rpath=dir`

fix missing - from rpath in pc files

---

resources/bitmaps/keyboard/export.sh
resources/bitmaps/keyboard/join.sh
resources/ui/carla_settings.ui
source/backend/CarlaBackend.h
source/backend/CarlaEngine.hpp
source/backend/CarlaHost.h
source/backend/CarlaPlugin.hpp
source/backend/CarlaStandalone.cpp
source/backend/engine/CarlaEngineData.cpp
source/backend/plugin/CarlaPluginVST2.cpp
source/bridges-plugin/CarlaBridgePlugin.cpp
source/frontend/carla_backend.py
source/frontend/carla_control.py
source/frontend/carla_skin.py
source/frontend/patchcanvas.py
source/frontend/patchcanvas/canvasport.py
source/frontend/patchcanvas/patchcanvas.py
source/interposer/interposer-jack-x11.cpp
source/jackbridge/JackBridge1.cpp
source/libjack/libjack.cpp
source/libjack/libjack_midi.cpp
source/theme/CarlaStyle.cpp
source/utils/CarlaJuceUtils.hpp
source/utils/CarlaLv2Utils.hpp

Found via `codepell` (v1.17.0.dev0)  
```
codespell -q 3 -L iff,iif,inport,sord,sinc,te,uint -S ./source/includes,./source/modules,./source/native-plugins,./data/windows
```

Fix source comment and user facing typos

---

source/frontend/carla_host.py

I find this icon :information_source: more fitting for the cancelable action, rather than using :x: which suggests error and it's a little confusing.

Change the dialog icon used for cancelable actions

---

source/modules/juce_audio_processors/Makefile
source/modules/juce_gui_basics/Makefile

GCC does not recognize the `-mbig-obj` MinGW flag, it should only be
added if DEBUG is true AND we are crosscompiling.

Fix JUCE compilation on Linux with DEBUG=true

---

resources/ui/carla_host.ui
source/frontend/carla_host.py

New options:
- Save: save the log to a file (default to carla_log.txt)
- Clear: clear the console log (also accessible via CTRL+L)
- Auto-Scroll (default on): chooses wether it should scroll to keep up with new log
entries or stay where it is
Misc:
- Small carla_host.ui cleanup (from Qt Designer)
- Do not show the console scrollbars when there is nothing to scroll
- Add some margin to the console to give it a more "console-like" feel
Closes  #839
Signed-off-by: Térence Clastres <t.clastres@gmail.com>

Add Save, Clear and toggle autoscroll to the Logs tab

---

source/frontend/widgets/pixmapdial.py

On some quirky Windows VST2 (old SWAM instruments) or old Linux ones (InsertPizHere plugins), a NaN parameter value would be sent.
This throws an error in the frontend code and prevent carla from creating the corresponding rack.
We workaround that by just returning early from PixmapDialsetValue() if the value is a NaN
Fixes #1143

VST2: Fix creation of a rack when one of the parameters is a NaN

---

source/includes/CarlaNative.h

With clang12, this ordering causes a big bunch of errors like:
```
In file included from midi-pattern.cpp:18:
In file included from ../includes/CarlaNativeExtUI.hpp:21:
In file included from ../includes/CarlaNative.hpp:21:
In file included from ../includes/CarlaNative.h:25:
In file included from ../includes/CarlaDefines.h:91:
/usr/include/c++/v1/cstddef:56:1: error: templates must have C++ linkage
template <class _Tp> struct __libcpp_is_integral                     { enum { value = 0 }; };
^~~~~~~~~~~~~~~~~~~~
../includes/CarlaNative.h:22:1: note: extern "C" language linkage specification begins here
extern "C" {
^
```

CarlaNative.h: move extern "C" after the includes to fix clang/libc++

---

source/frontend/carla_shared.py

The SF2 search path is missing a separator which results in a config file entry like 
`SF2=/home/faith/.sounds/sf2/home/faith/.sounds/sf3, /usr/share/soundfonts, /usr/share/sounds/sf2, /usr/share/sounds/sf3
`
by default. Note the missing comma between the first "sf2" and the following "/home"
This pull simply adds the missing ":" in the source.

Add missing separator in SF2 search path

---

Makefile

It's not possible to develop using carla-host-plugin without this header.

Install header CarlaPluginPtr.hpp

---

source/backend/plugin/CarlaPluginJSFX.cpp
source/backend/utils/CachedPlugins.cpp
source/discovery/carla-discovery.cpp
source/modules/jsusfx/source/jsusfx.cpp

This fix is for a variety of parameter update problems.
- After a change of slider, a flag must be set in the effect such that `@slider` is invoked on the next cycle. The new code uses the method `moveSlider`, which sets this flag.
- Set the sample rate early, before activate, such that the `@slider` code will see the value instead of 0, when it's invoked as part of `setChunkData`
- Set `@slider` update flag after a change of sample rate (jsusfx problem)
Edit
- set the scoped locale everywhere, before steps which involve parsing (compile / read header)

JSFX value updates

---

source/backend/plugin/CarlaPluginJSFX.cpp
source/backend/utils/CachedPlugins.cpp
source/discovery/carla-discovery.cpp
source/frontend/carla_database.py
source/utils/CarlaJsfxUtils.hpp
source/utils/CarlaStateUtils.cpp

#1487
This work would allow JSFX to be identified by their relative file ID.
This relative file ID is kept in the `label` field.
The JSFX unit will be identified by the pair of these two strings: root path, file ID
Their concatenation produces the full path.
A file ID is normalized to forward-slash separators.
The CarlaJsfxPlugin is edited such that it can load by either `filename` or `label`.
~~Draft because it's not tried yet.~~

jsfx: identification by relative path

---

source/modules/jsusfx/source/jsusfx.cpp
source/modules/jsusfx/source/jsusfx_file.cpp

This gets more MIDI plugins to work correctly. The changes are as follows:
- implement the missing API `midirecv_buf`
- fixes the implementation of `midisend_buf`, which is horrifyingly wrong
- allows to run FX which do not have `@sample` processing code, only `@block` (MIDI-only fx)

jsfx: fix various MIDI issues

---

source/backend/utils/CachedPlugins.cpp
source/discovery/carla-discovery.cpp
source/utils/CarlaJsfxUtils.hpp

This extracts commented metadata from jsfx files, and registers the author and category.
The functions which process this are utility implemented as part of carla, not the jsusfx library.

jsfx: parse the pseudo-tags for maker and category

---

source/backend/utils/CachedPlugins.cpp
source/discovery/carla-discovery.cpp
source/modules/jsusfx/source/jsusfx.cpp
source/utils/CarlaJsfxUtils.hpp

Some plugins that ship in Reaper (6 of them) would not scan because the syntax of Reaper is more permissive.
Example: `schwa/midi_modal_randomness`
One can omit the closing brace from the slider line.
`slider1:0<0,11,{1,1.5,2,2.5,3,4,4.5,5,5.5,6,6.5,7>Interval A`
This modifies jsusfx accordingly.

JSFX slider syntax fix for enums

---

source/modules/jsusfx/source/jsusfx.cpp
source/modules/jsusfx/source/jsusfx.h

This registers the `atomic` methods in the jsusfx EEL runtime.
This makes plugin Cockos `loopsamplers/super8` runnable, which requires `atomic_exchg`.

jsfx: add support of atomic methods

---

source/frontend/patchcanvas/scene.py

Under certain circumstances Carla would crash when frequent updates on
the QGraphicsScene occurred, especially in combination with scrolling or
panning by the user. Backtraces showed either a segfault in
QGraphicsItem::parentItem() or around
QGraphicsSceneBspTree::climbTree(). While the first trace points towards
missing calls to pepareGeometryChange() in combination with custom
boundingRect() methods, inserting these did not yield a positive change,
though people with this issue also had success in disabling the
ItemIndexingMethod of their QGraphicsScene[0][1]. Setting this to
NoIndex solves this problem.
The original problem is reproducible with an ever-reconnecting client:
$ while true; do klick 120 & (sleep 0.1; killall klick); done
[0] …

Disable GraphicsScene indexing method to prevent crashes

---

source/backend/plugin/CarlaPluginJSFX.cpp
source/modules/jsusfx/source/jsusfx.cpp

This enables to run more jsfx plugins.
example: `loser/DDC` (Digital Drum Compressor)
These files have an unspecified slider notation which omits the `<>` part.
eg. `slider10:0,Reduction (dB)`
These sliders without a range are given a default [0;1].
The scope of this PR does not extend to output control automations, which will be for a next one.

jsfx: parse more forms of sliders

---

source/backend/plugin/CarlaPluginJSFX.cpp
source/modules/jsusfx/source/jsusfx.cpp
source/modules/jsusfx/source/jsusfx.h

Followup to #1516 which updates output parameters.
Implements Reaper API `sliderchange`.
It accepts either a bitmap or a slider as the argument, which lead to different behavior in each case.
To make that work efficiently, it needs a mapping from variable (EEL_F*) to slider, which is introduced as a hash table.
This involves a bitmap of changed sliders, and 1-indexing weirdness.
Added a few comments to clarify.

jsfx: output parameter changes

---

source/frontend/carla_shared.py

These days there is pipewire, which provides backends for PulseAudio, ALSA and JACK. Usually, if one is using pipewire as a replacement for the former three, they want to run Carla with the JACK backend mode since it is the most compatible and allows managing pipewire connections.
If the pipewire jack backend is installed can be detected by checking if `/usr/bin/pw-jack` exists, so I added it to the check.

detect pipewire jack backend for better defaults

---

source/frontend/widgets/scalabledial.py

Fixes this error, which would occur after `setPrecision` had been called
with a non-integer value.
```
Traceback (most recent call last):
File "/usr/share/carla/carla_host.py", line 1442, in slot_handlePluginAddedCallback
pitem = self.ui.listWidget.createItem(pluginId, self.fSavedSettings[CARLA_KEY_MAIN_CLASSIC_SKIN])
File "/usr/share/carla/widgets/racklistwidget.py", line 241, in createItem
return RackListItem(self, pluginId, useClassicSkin)
File "/usr/share/carla/widgets/racklistwidget.py", line 86, in __init__
self.recreateWidget(firstInit = True)
File "/usr/share/carla/widgets/racklistwidget.py", line 176, in recreateWidget
self.fWidget = createPluginSlot(self.fParent, self.host, self.fPluginId, self.fOptions)
File "/usr/share/carla/carla_skin.py", line 2090, in createPluginSlot …
```

Cast QDial value parameter to prevent type error

---

source/frontend/patchcanvas/canvasbox.py

The `CanvasBox.positionChanged` signal expects to receive `x` and `y` as
`int`s, but they were being passed as `float`s, which were mangled at the
receiving signal handler.
This manifested as huge `x` and `y` values for canvas boxes, and when
saving and loading projects all boxes would hit the edge of the canvas
and get placed at the extreme edge.

Fix type error in signal emission

---

source/backend/engine/CarlaEngineData.cpp
source/backend/plugin/CarlaPluginBridge.cpp
source/backend/plugin/CarlaPluginFluidSynth.cpp
source/backend/plugin/CarlaPluginJack.cpp
source/backend/plugin/CarlaPluginJuce.cpp
source/backend/plugin/CarlaPluginLADSPADSSI.cpp
source/backend/plugin/CarlaPluginLV2.cpp
source/backend/plugin/CarlaPluginNative.cpp
source/backend/plugin/CarlaPluginSFZero.cpp
source/backend/plugin/CarlaPluginVST2.cpp

This fixes the inaccuracies in midi controller values which are introduced by converting them to the float range 0.0 -- 1.0 and back again. The problem is that `int((18 / 127.0) * 127.0) != 18`. (it's 17, because the float result is something like 17.9999998)
It can be fixed by properly rounding to the nearest integer, instead of rounding down. This is accomplished by the usual "add 0.5" trick.
`modules/sfzero/sfzero/SFZ{Synth,Voice}.cpp` exhibit a similar problem, but were not touched in this PR, because they're not part of the engine and we might want to stay bug-to-bug compatible with the upstream plugin.
This might resolve #1249 and might resolve #899.

Fix inaccurate midi CC rounding

---

data/pkgconfig/carla-host-plugin.pc
data/pkgconfig/carla-native-plugin.pc
data/pkgconfig/carla-standalone.pc
data/pkgconfig/carla-utils.pc

The pkgconfig files are installed in `$PREFIX/lib` so using `libdir=${prefix}/lib/carla` is confusing.
Most software pkgconfig files seem to match the includedir and libdir variables with the actual includedir and libdir during configuration.

fix pkgconfig files having bad includedir/libdir variables

---

Makefile

latest main branch fails during `make install` without this

fix make install (missing pluginlist dir)

---

source/frontend/widgets/canvaspreviewframe.py

Using the small canvaspreview to pan the patchbay resulted in an exception when panning out of bounds of the window. In this case Carla tried to create a QPoint with two floats, for which qt has no constructor. This results in the panning to hang, as the event is "handled" with an exception.
Casting these two values to int lets qt create the QPoint and with that properly set the new cursor position, so panning can be done in all edges again, without having to be precise with the cursor positioning.
This is probably a left-over from a python2 to python3 migration, as python did integer divison by default.
---
Exception on my machine without the patch:
```
Traceback (most recent call last):
File "/home/seba/projects/src/carla/source/frontend/widgets/canvaspreviewframe.py", line 180, in …
```

Fix canvaspreview out-of-bounds panning for patchbay

---

source/frontend/carla_host.py

I read this issue https://github.com/falkTX/Carla/issues/1568, because I was running into a similar issue. Now that I had some time to poke the code, I noticed a relatively simple solution to my problem.
This should allow modifying the name of the pipewire/jack device when running headless mode with the same configuration option as when running with UI mode enabled.
Setting `CARLA_CLIENT_NAME` to any value will make the devices pick up that name instead of the default `"Carla"`.

Allow configuration of Carla client name when headless

---

source/modules/water/files/File.cpp

Musl 1.2.4 gated the LFS64 compatibility shims behind the _LARGEFILE64_SOURCE macro, and they will be removed entirely in musl 1.2.5. Instead, always use the normal stat function instead of stat64, and set -D_FILE_OFFSET_BITS=64, which ensures that functions will always be 64-bits on 32-bit glibc platforms (and does nothing on other platforms).

Fix build with musl libc 1.2.4

---

cmake/CMakeLists.txt
cmake/carla-host-plugin.pc.in
cmake/carla-native-plugin.pc.in
cmake/carla-standalone.pc.in

This installs the missing pkgconfig files for host-plugin/native-plugin/standalone libraries.
carla-host-plugin.pc looks like this when installed (in prefix `/tmp/carlatest`):
```
prefix=/tmp/carlatest
libdir=/tmp/carlatest/lib
includedir=/tmp/carlatest/include
carla_libdir=${libdir}/carla
Name: carla-host-plugin
Version: 2.6.0-alpha1
Description: Carla Host as Native Plugin
Libs: -Wl,-rpath,${carla_libdir} -L${carla_libdir} -lcarla_host-plugin
Cflags: -I${includedir}/carla -I${includedir}/carla/includes
```

cmake: Install host-plugin/native-plugin/standalone pkgconfig files

---

source/includes/lv2/atom-helpers.h

Fixes #1902
Added _alignment_padding to _LV2_Atom_Buffer.
from,
https://lv2plug.in/ns/ext/atom
"An LV2_Atom has a 32-bit size and type, followed by a body of size bytes. Atoms MUST be 64-bit aligned."

Fix misaligned LV2 Atoms

---

resources/ui/carla_settings.ui

The port number boxes had the Max Parameters tooltip copied over, removed it.

Remove some untrue tooltips from OSC config

---

source/frontend/carla_host_control.py

pyliblo has not been touched upstream since 2015 and doesn't work out of the box with Python releases since 3.11. There is an actively-maintained fork called 'pyliblo3' at
https://github.com/gesellkammer/pyliblo3 which *does* work with current upstream Python releases. It provides a library called 'pyliblo3' rather than 'liblo'. Let's support it, and prefer it over the dead library (though the dead one will still be used if it is present and pyliblo3 is not).

carla_host_control: import from pyliblo3 if available

---

source/backend/plugin/CarlaPluginJack.cpp

It appears to simply be a typo. MAP_PROGRAM_CHANGES is not an available option for Jack applications, only SEND_PROGRAM_CHANGES is.

Fix broken program and bank messages for Jack applications.
